#!/bin/sh

branch=$(git rev-parse --abbrev-ref HEAD)

if [[ "$branch" =~ ^(dev|main|stg)$ ]]; then
  echo "❌ Error: You cannot commit directly to '$branch'."
  exit 1
fi

if grep -rE "<<<<<<<|=======|>>>>>>>" src/; then
  echo "❌ Error: Git conflict markers were detected. Clean up your code!"
  exit 1
fi


find_large_files=$(git diff --cached --name-only | xargs -I {} find {} -size +5M)
if [ -n "$find_large_files" ]; then
  echo "❌ Error: You are trying to upload files larger than 5MB: $find_large_files"
  echo "Use Git LFS or compress the files."
  exit 1
fi

echo "🌿 Branch detected: $branch"

echo "🎨 [1/3] Applying code formatting (Spotless)..."
./mvnw spotless:apply -ntp

git add -u

echo "🔍 [2/3] Validating quality rules (Checkstyle)..."
if ! ./mvnw checkstyle:check -ntp; then
    echo "❌ Error: The code does not comply with Checkstyle rules."
    echo "Check the report in target/checkstyle-result.xml or the logs above."
    exit 1
fi

echo "✅ [3/3] Final Spotless Verification..."
if ! ./mvnw spotless:check -ntp; then
    echo "❌ Error: Spotless final validation failed."
    exit 1
fi

echo "🚀 Quality verified! Creating commit..."