name: CD - Docker Release to GHCR

on:
  workflow_run:
    workflows: ["CI - Quality & Build"]
    types: [completed]
    branches: ["prod", "dev", "pre"]

permissions:
  packages: write
  contents: read

jobs:
  deploy-to-ghcr:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Extract branch name
        id: branch-step
        run: |
          echo "branch=${{ github.event.workflow_run.head_branch }}" >> $GITHUB_OUTPUT

      - name: Download JAR from CI
        uses: actions/download-artifact@v4
        with:
          name: ecommerce-release
          run_id: ${{ github.event.workflow_run.id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path: target/

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/ecommerce:${{ steps.branch-step.outputs.branch }}
            ghcr.io/${{ github.repository_owner }}/ecommerce:${{ github.event.workflow_run.head_sha }}
            ${{ steps.branch-step.outputs.branch == 'prod' && format('ghcr.io/{0}/ecommerce:latest', github.repository_owner) || '' }}